# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(711, 642)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_action = QtWidgets.QTabWidget(self.centralwidget)
        self.choose_action.setEnabled(True)
        self.choose_action.setGeometry(QtCore.QRect(0, 0, 711, 602))
        self.choose_action.setTabPosition(QtWidgets.QTabWidget.North)
        self.choose_action.setObjectName("choose_action")
        self.select_db = QtWidgets.QWidget()
        self.select_db.setObjectName("select_db")
        self.choose_action.addTab(self.select_db, "")
        self.update_db = QtWidgets.QWidget()
        self.update_db.setObjectName("update_db")
        self.update_tables = QtWidgets.QTabWidget(self.update_db)
        self.update_tables.setGeometry(QtCore.QRect(0, 0, 711, 602))
        self.update_tables.setObjectName("update_tables")
        self.update_users = QtWidgets.QWidget()
        self.update_users.setObjectName("update_users")
        self.update_tables.addTab(self.update_users, "")
        self.update_games = QtWidgets.QWidget()
        self.update_games.setObjectName("update_games")
        self.update_tables.addTab(self.update_games, "")
        self.update_currencies = QtWidgets.QWidget()
        self.update_currencies.setObjectName("update_currencies")
        self.update_tables.addTab(self.update_currencies, "")
        self.update_genres = QtWidgets.QWidget()
        self.update_genres.setObjectName("update_genres")
        self.update_tables.addTab(self.update_genres, "")
        self.update_friends = QtWidgets.QWidget()
        self.update_friends.setObjectName("update_friends")
        self.update_tables.addTab(self.update_friends, "")
        self.update_platforms = QtWidgets.QWidget()
        self.update_platforms.setObjectName("update_platforms")
        self.update_tables.addTab(self.update_platforms, "")
        self.update_users_games = QtWidgets.QWidget()
        self.update_users_games.setObjectName("update_users_games")
        self.update_tables.addTab(self.update_users_games, "")
        self.update_transactions = QtWidgets.QWidget()
        self.update_transactions.setObjectName("update_transactions")
        self.update_tables.addTab(self.update_transactions, "")
        self.update_games_platforms = QtWidgets.QWidget()
        self.update_games_platforms.setObjectName("update_games_platforms")
        self.update_tables.addTab(self.update_games_platforms, "")
        self.choose_action.addTab(self.update_db, "")
        self.delete_db = QtWidgets.QWidget()
        self.delete_db.setObjectName("delete_db")
        self.delete_tables = QtWidgets.QTabWidget(self.delete_db)
        self.delete_tables.setGeometry(QtCore.QRect(0, 0, 711, 602))
        self.delete_tables.setObjectName("delete_tables")
        self.delete_users = QtWidgets.QWidget()
        self.delete_users.setObjectName("delete_users")
        self.delete_tables.addTab(self.delete_users, "")
        self.delete_games = QtWidgets.QWidget()
        self.delete_games.setObjectName("delete_games")
        self.delete_tables.addTab(self.delete_games, "")
        self.delete_currencies = QtWidgets.QWidget()
        self.delete_currencies.setObjectName("delete_currencies")
        self.delete_tables.addTab(self.delete_currencies, "")
        self.delete_genres = QtWidgets.QWidget()
        self.delete_genres.setObjectName("delete_genres")
        self.delete_tables.addTab(self.delete_genres, "")
        self.delete_friends = QtWidgets.QWidget()
        self.delete_friends.setObjectName("delete_friends")
        self.delete_tables.addTab(self.delete_friends, "")
        self.delete_platforms = QtWidgets.QWidget()
        self.delete_platforms.setObjectName("delete_platforms")
        self.delete_tables.addTab(self.delete_platforms, "")
        self.delete_users_games = QtWidgets.QWidget()
        self.delete_users_games.setObjectName("delete_users_games")
        self.delete_tables.addTab(self.delete_users_games, "")
        self.delete_transactions = QtWidgets.QWidget()
        self.delete_transactions.setObjectName("delete_transactions")
        self.delete_tables.addTab(self.delete_transactions, "")
        self.delete_games_platforms = QtWidgets.QWidget()
        self.delete_games_platforms.setObjectName("delete_games_platforms")
        self.delete_tables.addTab(self.delete_games_platforms, "")
        self.choose_action.addTab(self.delete_db, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 711, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.choose_action.setCurrentIndex(2)
        self.update_tables.setCurrentIndex(1)
        self.delete_tables.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_action.setTabText(self.choose_action.indexOf(self.select_db), _translate("MainWindow", "Wyświetl"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_users), _translate("MainWindow", "Użytkownicy"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_games), _translate("MainWindow", "Gry"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_currencies), _translate("MainWindow", "Waluty"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_genres), _translate("MainWindow", "Gatunki"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_friends), _translate("MainWindow", "Znajomi"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_platforms), _translate("MainWindow", "Platformy"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_users_games), _translate("MainWindow", "Gry użytkoników"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_transactions), _translate("MainWindow", "Transakcje"))
        self.update_tables.setTabText(self.update_tables.indexOf(self.update_games_platforms), _translate("MainWindow", "Platformy z grami"))
        self.choose_action.setTabText(self.choose_action.indexOf(self.update_db), _translate("MainWindow", "Aktualizuj"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_users), _translate("MainWindow", "Użytkownicy"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_games), _translate("MainWindow", "Gry"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_currencies), _translate("MainWindow", "Waluty"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_genres), _translate("MainWindow", "Gatunki"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_friends), _translate("MainWindow", "Znajomi"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_platforms), _translate("MainWindow", "Platformy"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_users_games), _translate("MainWindow", "Gry użytkoników"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_transactions), _translate("MainWindow", "Transakcje"))
        self.delete_tables.setTabText(self.delete_tables.indexOf(self.delete_games_platforms), _translate("MainWindow", "Platformy z grami"))
        self.choose_action.setTabText(self.choose_action.indexOf(self.delete_db), _translate("MainWindow", "Usuń"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
